ALTER TABLE seasons ADD COLUMN registrations_open_at timestamptz;
ALTER TABLE seasons ADD COLUMN purge_at timestamptz;
UPDATE seasons SET registrations_open_at=opens_at-interval '30 days',purge_at=closes_at+interval '36 hours';
ALTER TABLE seasons ALTER COLUMN registrations_open_at SET NOT NULL;
ALTER TABLE seasons ALTER COLUMN purge_at SET NOT NULL;
ALTER TABLE seasons ADD CONSTRAINT season_dates CHECK(registrations_open_at<=opens_at AND closes_at<=purge_at);
CREATE TABLE bootstrap(singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),secret_hash text NOT NULL,consumed_at timestamptz,invalidated_at timestamptz);
CREATE TABLE setup_sessions(token_hash text PRIMARY KEY,expires_at timestamptz NOT NULL);
ALTER TABLE sessions ADD COLUMN preview_at timestamptz;
UPDATE roles SET permissions=array_append(permissions,'season.preview') WHERE name IN('SUPER_ADMIN','LOCAL_ADMIN') AND NOT('season.preview'=ANY(permissions));
ALTER TABLE seasons ADD COLUMN reminder_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE seasons ADD COLUMN reminder_at timestamptz;
ALTER TABLE seasons ADD COLUMN reminder_subject text NOT NULL DEFAULT '';
ALTER TABLE seasons ADD COLUMN reminder_body text NOT NULL DEFAULT '';
ALTER TABLE seasons ADD COLUMN reminder_status text NOT NULL DEFAULT 'NONE' CHECK(reminder_status IN('NONE','SCHEDULED','SENDING','SENT','ERROR'));
ALTER TABLE seasons ADD COLUMN reminder_recipients integer NOT NULL DEFAULT 0;
ALTER TABLE seasons ADD COLUMN reminder_sent integer NOT NULL DEFAULT 0;
ALTER TABLE seasons ADD COLUMN reminder_sent_at timestamptz;
CREATE TABLE reminder_deliveries(season_id uuid NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,status text NOT NULL DEFAULT 'QUEUED' CHECK(status IN('QUEUED','CLAIMED','SENT','ERROR')),claimed_at timestamptz,PRIMARY KEY(season_id,user_id));
