export const auditLabels: Record<string, string> = {
  "preview.enabled": "Accès anticipé activé",
  "preview.disabled": "Accès anticipé désactivé",
  "house.review.validated": "Maison validée",
  "house.review.refused": "Maison refusée",
  "house.review.pending": "Maison remise en attente",
  "house.updated": "Maison modifiée",
  "house.visible": "Maison affichée",
  "house.hidden": "Maison masquée",
  "participant.created": "Maison inscrite",
  "participant.deleted": "Maison supprimée",
  "participant.end": "Maison fermée",
  "participant.resume": "Maison rouverte",
  "participant.pause": "Accueil suspendu",
  "participant.candy": "Disponibilité des bonbons modifiée",
  "participant.noCandy": "Bonbons épuisés",
  "participant.no_candy": "Bonbons épuisés",
  "house.activity.closed": "Maison fermée",
  "season.activated": "Saison activée",
  "season.updated": "Saison modifiée",
  "season.test.selected": "Saison TEST sélectionnée",
  "season.test.deleted": "Saison TEST supprimée",
  "user.created": "Utilisateur créé",
  "participant.deplete": "Bonbons épuisés",
  "user.invite": "Utilisateur invité",
  "user.edit": "Utilisateur modifié",
  "user.disable": "Compte suspendu",
  "user.enable": "Compte activé",
  "user.delete": "Utilisateur supprimé",
  "user.invited": "Utilisateur invité",
  "user.updated": "Utilisateur modifié",
  "user.deleted": "Utilisateur supprimé",
  "settings.updated": "Paramètres modifiés",
  "route.created": "Parcours créé",
  "route.completed": "Parcours terminé",
};
export function auditLabel(action: string) {
  return auditLabels[action] ?? "Action administrative enregistrée";
}
export const permissionLabels: Record<string, string> = {
  "admin.access": "Accéder à l’administration",
  "communications.read": "Consulter les communications",
  "communications.manage": "Gérer les communications",
  "content.manage": "Gérer les textes et documents",
  "participants.read": "Consulter les maisons",
  "participants.edit": "Modifier et modérer les maisons",
  "participants.delete": "Supprimer les maisons",
  "users.read": "Consulter les utilisateurs",
  "users.manage": "Gérer les utilisateurs",
  "season.read": "Consulter les saisons",
  "season.manage": "Gérer et activer les saisons",
  "season.preview": "Gérer l’accès anticipé",
  "settings.read": "Consulter les paramètres",
  "settings.manage": "Modifier les paramètres",
  "stats.read": "Consulter les statistiques",
  "audit.read": "Consulter l’activité",
  "roles.manage": "Attribuer les rôles d’équipe",
};
